### ISSUE TITLE
Not working since July 1st because the Notion-Version header is not set

### ISSUE THREAD

**Issue by benthillerkus** [jonathangomz/notion_api#8]
It seems there is already a PR for this with #7

[https://developers.notion.com/changelog/unversioned-requests-no-longer-accepted](https://developers.notion.com/changelog/unversioned-requests-no-longer-accepted)

**Comment by jonathangomz** [comment]
Thaaaanks, I'm not used to receive contributions hehe It feel nice, I will chek the PR right now

**Comment by jonathangomz** [comment]
It's ready and publish thanks for the @bagaswastu help :)
